name: Swagger

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Swagger ui action
        id: swagger-ui-action
        uses: pjoc-team/swagger-ui-action@v0.0.2
        with:
          dir: './api/swagger/'
          pattern: '*.json'
          debug: 'true'
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: swagger-ui
      - name: File Diff
        uses: tianhaoz95-actions/file-diff@v1.0.0
        with: 
          lhs: './api/swagger/asd.yml'
          rhs: './api/swagger/swagger.yaml'
          compare: true
          

